ALTER TABLE public.tickets REPLICA IDENTITY FULL;
ALTER TABLE public.shift_reports REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER TABLE public.user_activity_logs REPLICA IDENTITY FULL;